services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: poll-backend
    ports:
      - "3005:3005"
    environment:
      - PORT=3005
      - CORS_ORIGIN=http://localhost:5173,http://localhost:3000
      - MONGODB_URI=mongodb://poll-mongo:27017/polling-system
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - poll-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=http://localhost:3005
        - VITE_SOCKET_URL=http://localhost:3005
    container_name: poll-frontend
    ports:
      - "5173:5173"
    # depends_on:
    #   - mongo
    restart: unless-stopped
    networks:
      - poll-network

  mongo:
    image: mongo:7
    container_name: poll-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    networks:
      - poll-network

volumes:
  mongo-data:

networks:
  poll-network:
    driver: bridge
